
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ROSE
 */
public class NewFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewFrame
     */
    public NewFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        laysRB = new javax.swing.JRadioButton();
        balajiRB = new javax.swing.JRadioButton();
        kurkureRB = new javax.swing.JRadioButton();
        redbullRB = new javax.swing.JRadioButton();
        mountaindewRB = new javax.swing.JRadioButton();
        thumpsupRB = new javax.swing.JRadioButton();
        purchaseBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        moneyTF = new javax.swing.JTextField();
        changeTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vending Machine");
        setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel1.setText("VENDING MACHINE");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select an item", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14))); // NOI18N

        laysRB.setText("Lays  $1.2");
        laysRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laysRBActionPerformed(evt);
            }
        });

        balajiRB.setText("Balaji $1.3");
        balajiRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balajiRBActionPerformed(evt);
            }
        });

        kurkureRB.setText("Kurkure $1.22");
        kurkureRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurkureRBActionPerformed(evt);
            }
        });

        redbullRB.setText("Red Bull $1.23");
        redbullRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redbullRBActionPerformed(evt);
            }
        });

        mountaindewRB.setText("Mountain Dew $1.1");
        mountaindewRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mountaindewRBActionPerformed(evt);
            }
        });

        thumpsupRB.setText("Thumps up $1.27");
        thumpsupRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thumpsupRBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(redbullRB)
                        .addGap(49, 49, 49))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(laysRB)
                        .addGap(65, 65, 65)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(balajiRB)
                    .addComponent(mountaindewRB))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(thumpsupRB)
                    .addComponent(kurkureRB))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(laysRB, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kurkureRB))
                        .addGap(18, 18, 18)
                        .addComponent(thumpsupRB))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(balajiRB)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(redbullRB)
                            .addComponent(mountaindewRB))))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        purchaseBtn.setText("Purchase");
        purchaseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Insert Money :");

        jLabel3.setText("Change :");

        moneyTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moneyTFActionPerformed(evt);
            }
        });

        changeTF.setEditable(false);
        changeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(purchaseBtn)
                                    .addGap(170, 170, 170)
                                    .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(61, 61, 61)
                                .addComponent(changeTF))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(34, 34, 34)
                                .addComponent(moneyTF, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(moneyTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(changeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(purchaseBtn)
                    .addComponent(clearBtn)
                    .addComponent(cancelBtn))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void laysRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laysRBActionPerformed
        // changing radio buttons to select one
        
        if(laysRB.isSelected())
        {
            balajiRB.setSelected(false);
             kurkureRB.setSelected(false);
                redbullRB.setSelected(false);
            mountaindewRB.setSelected(false);
            thumpsupRB.setSelected(false);
        }
    }//GEN-LAST:event_laysRBActionPerformed

    private void balajiRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balajiRBActionPerformed
        // TODO add your handling code here:
         if(balajiRB.isSelected())
        {
             laysRB.setSelected(false);
             kurkureRB.setSelected(false);
                redbullRB.setSelected(false);
            mountaindewRB.setSelected(false);
            thumpsupRB.setSelected(false);
        }
    }//GEN-LAST:event_balajiRBActionPerformed

    private void moneyTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moneyTFActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_moneyTFActionPerformed

    private void changeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changeTFActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // cancel selections
        
        System.exit(0);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // clears all selections and text fields
        
        laysRB.setSelected(false);
       balajiRB.setSelected(false);
        kurkureRB.setSelected(false);
        redbullRB.setSelected(false);
        mountaindewRB.setSelected(false);
        thumpsupRB.setSelected(false);
        
        moneyTF.setText(" ");
        changeTF.setText(" ");
    }//GEN-LAST:event_clearBtnActionPerformed

    private void kurkureRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurkureRBActionPerformed
        // TODO add your handling code here:
         if(kurkureRB.isSelected())
        {
             laysRB.setSelected(false);
             balajiRB.setSelected(false);
                redbullRB.setSelected(false);
            mountaindewRB.setSelected(false);
            thumpsupRB.setSelected(false);
        }
    }//GEN-LAST:event_kurkureRBActionPerformed

    private void redbullRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redbullRBActionPerformed
            // TODO add your handling code here:
            if(redbullRB.isSelected())
        {
             laysRB.setSelected(false);
             balajiRB.setSelected(false);
                kurkureRB.setSelected(false);
            mountaindewRB.setSelected(false);
            thumpsupRB.setSelected(false);
        }
    }//GEN-LAST:event_redbullRBActionPerformed

    private void mountaindewRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mountaindewRBActionPerformed
            // TODO add your handling code here:
               if(mountaindewRB.isSelected())
        {
             laysRB.setSelected(false);
             balajiRB.setSelected(false);
                kurkureRB.setSelected(false);
           redbullRB.setSelected(false);
            thumpsupRB.setSelected(false);
        }
    }//GEN-LAST:event_mountaindewRBActionPerformed

    private void thumpsupRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thumpsupRBActionPerformed
        // TODO add your handling code here:
               if(thumpsupRB.isSelected())
        {
             laysRB.setSelected(false);
             balajiRB.setSelected(false);
                kurkureRB.setSelected(false);
           redbullRB.setSelected(false);
            mountaindewRB.setSelected(false);
        }
    }//GEN-LAST:event_thumpsupRBActionPerformed

    private void purchaseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseBtnActionPerformed
        // this pays for our purchase if we have enough money
        
       double money = 0;
       
       money = Double.parseDouble(moneyTF.getText());
       
       if(laysRB.isSelected())
       {
           money = money - 1.25;
       }
       else if(balajiRB.isSelected()){
           
           money= money - 1.3;
           
       }
        else if(kurkureRB.isSelected()){
           
           money= money - 1.22;
           
       }
        else if(redbullRB.isSelected()){
           
           money= money - 1.23;
           
       }
        else if(mountaindewRB.isSelected()){
           
           money= money - 1.11;
           
       }
        else if(thumpsupRB.isSelected()){
           
           money= money - 1.27;
           
       }
       
       if(money < 0)
       {
           JOptionPane.showMessageDialog(rootPane, "Sorry you donot have enough money");
       }else{
           changeTF.setText(Double.toString(money));
       }
    }//GEN-LAST:event_purchaseBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton balajiRB;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField changeTF;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton kurkureRB;
    private javax.swing.JRadioButton laysRB;
    private javax.swing.JTextField moneyTF;
    private javax.swing.JRadioButton mountaindewRB;
    private javax.swing.JButton purchaseBtn;
    private javax.swing.JRadioButton redbullRB;
    private javax.swing.JRadioButton thumpsupRB;
    // End of variables declaration//GEN-END:variables
}
